name = "OwnTime"
uuid = "18732c20-e27e-497f-aa49-3bf01a8fc721"
authors = ["Devin Jacobs <dbuttonz@gmail.com>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
